#!/usr/bin/env python3
"""
Test script to verify that diagrams generated by resetters have flow.
"""

import numpy as np
from zxreinforce.Resetters import Resetter_ZERO_PI_PIHALF_ARB_hada, Resetter_FlowPatterns
from zxreinforce.flow_checking import has_flow
from zxreinforce.own_constants import INPUT, OUTPUT

def test_resetter_flow(resetter_class, resetter_name, n_tests=10):
    """Test if a resetter generates diagrams with flow."""
    print(f"\n{'='*60}")
    print(f"Testing {resetter_name}")
    print(f"{'='*60}")
    
    # Create resetter
    rng = np.random.default_rng(42)  # Fixed seed for reproducibility
    
    if resetter_name == "Resetter_ZERO_PI_PIHALF_ARB_hada":
        resetter = resetter_class(
            n_in_min=1,
            n_in_max=3,
            min_spiders=5,
            max_spiders=15,
            pi_fac=0.5,
            pi_half_fac=0.5,
            arb_fac=0.5,
            p_hada=0.1,
            min_mean_neighbours=2,
            max_mean_neighbours=4,
            rng=rng
        )
    else:  # Resetter_FlowPatterns
        resetter = resetter_class(
            n_in_min=1,
            n_in_max=3,
            n_out_min=1,
            n_out_max=3,
            n_layers_min=2,
            n_layers_max=5,
            nodes_per_layer_min=2,
            nodes_per_layer_max=5,
            pi_fac=0.5,
            pi_half_fac=0.5,
            arb_fac=0.5,
            p_hada=0.1,
            p_edge=0.3,
            rng=rng
        )
    
    flow_count = 0
    no_flow_count = 0
    
    for i in range(n_tests):
        try:
            colors, angles, selected_node, source, target, selected_edges = resetter.reset()
            
            # Check flow
            has_flow_result = has_flow(colors, source, target, INPUT, OUTPUT)
            
            if has_flow_result:
                flow_count += 1
                print(f"  Test {i+1}: ✓ Has flow (nodes: {len(colors)}, edges: {len(source)})")
            else:
                no_flow_count += 1
                print(f"  Test {i+1}: ✗ NO FLOW (nodes: {len(colors)}, edges: {len(source)})")
                
                # Debug: check inputs/outputs
                input_indices = np.where(np.all(colors == INPUT, axis=1))[0]
                output_indices = np.where(np.all(colors == OUTPUT, axis=1))[0]
                print(f"    Inputs: {len(input_indices)}, Outputs: {len(output_indices)}")
                
        except Exception as e:
            print(f"  Test {i+1}: ERROR - {e}")
            no_flow_count += 1
    
    print(f"\n  Results: {flow_count}/{n_tests} diagrams have flow ({100*flow_count/n_tests:.1f}%)")
    if no_flow_count > 0:
        print(f"  WARNING: {no_flow_count} diagrams without flow!")
    
    return flow_count == n_tests

if __name__ == "__main__":
    print("Testing flow generation in resetters...")
    print("This will generate diagrams and check if they have flow.\n")
    
    # Test both resetters
    test1_passed = test_resetter_flow(
        Resetter_ZERO_PI_PIHALF_ARB_hada, 
        "Resetter_ZERO_PI_PIHALF_ARB_hada",
        n_tests=20
    )
    
    test2_passed = test_resetter_flow(
        Resetter_FlowPatterns,
        "Resetter_FlowPatterns",
        n_tests=20
    )
    
    print(f"\n{'='*60}")
    print("SUMMARY")
    print(f"{'='*60}")
    print(f"Resetter_ZERO_PI_PIHALF_ARB_hada: {'PASS' if test1_passed else 'FAIL'}")
    print(f"Resetter_FlowPatterns: {'PASS' if test2_passed else 'FAIL'}")
    
    if test1_passed and test2_passed:
        print("\n✓ All tests passed! Diagrams have flow.")
    else:
        print("\n✗ Some tests failed. Some diagrams don't have flow.")







